---
title: "Melton_Worksheet2&3"
format: html
editor: visual
---

------------------------------------------------------------------------

## [9/19/2024 - Disease Ecology - Worksheet 2 & 3]{.underline}

**1) Find the sample size necessary to detect a disease at or above 5% prevalence in a\
herd of 5000 deer. The desired level of confidence is 95%.**

The necessary sample size is 59.

<https://github.com/jakemelton02/DiseaseEcologyFall2024/blob/main/Table1.png>\

------------------------------------------------------------------------

**2) Using the hypergeometric distribution, compare the sample size requirements for the\
following scenarios:**\

[a) 95% confidence in detecting a disease at 1% prevalence in a large population]{.underline}

Sample size requirements: 299

\

[b) 99% confidence in detecting a disease at 2% prevalence in a large population]{.underline}

Sample size requirements: 458

------------------------------------------------------------------------

\

**3) You sample 300 deer from a high fenced facility that has a herd of 4000. None of the\
300 have antibodies against Epizootic Hemorrhagic Disease. Based on this finding, you\
are 95% confident that the prevalence of exposure to EHD in this facility is \_\_\<\_\_\_ (\<, =,\>) \_\_1\_\_%.**

Rule of 3: 3/N

Sampled deer (N): 300

3/300=0.01 or 1%

------------------------------------------------------------------------

\

**4) An outbreak of ‘Lame disease’ has been reported in wild turkey populations of\
Alabama. Turkeys from three counties were sampled for lameness (Lee, Chambers and\
Russell counties).**\

[a) Analyze the sample data to determine prevalence of lameness in each county. Provide confidence interval for prevalence using Sterne’s method.]{.underline}

| County   | Prevalence (Sterne's Method) | 95% Cl    |
|----------|------------------------------|-----------|
| Lee      | 20%                          | (14%-27%) |
| Chambers | 27%                          | (13%-45%) |
| Russell  | 3%                           | (1%-8.7%) |

[\
b) Compare prevalences using Fisher’s exact test.]{.underline}

| County   | Prevalence (Fisher's Exact Test) |
|----------|----------------------------------|
| Chambers | 27%                              |
| Lee      | 20%                              |

-   p-value= .46

    -   The p-value is greater than 0.05. Therefore, the difference is not statistically significant.

| County   | Prevalence (Fisher's Exact Test) |
|----------|----------------------------------|
| Chambers | 27%                              |
| Russell  | 3%                               |

-   p-value: 0.0004

the p-value is less than 0.05. Therefore, the difference is statistically significant.

------------------------------------------------------------------------

**5) Jane was studying the spread of Pink Spot Disease (PSD) in a pond that had 60 fish.\
She introduced an infectious fish in the pond on day 0. Her observations are as follows:**\

**Day 1: 3 fish infected**

**Day 2: 4 fish infected**

**Day 3: 7 fish infected**

**Day 4: 11 fish infected**

**Day 5: 20 fish infected**

[**Note that there is no disease-related mortality. The observations denote all infected fish\
in the pond (including previously infected fish).**]{.underline}

| Day  | Susceptible  | Total Infected | New Infections | Incidence | Prevalence  |
|------|--------------|----------------|----------------|-----------|-------------|
| 1    | 60           | 3              | 3              | 0.05      | 0.05        |
| 2    | 57           | 4              | 1              | 0.02      | 0.07        |
| 3    | 53           | 7              | 3              | 0.06      | 0.12        |
| 4    | 46           | 11             | 4              | 0.09      | 0.18        |
| 5    | 35           | 20             | 9              | 0.26      | 0.33        |

[a) Find incidence on day 1, day 2 and day 5. Write the unit for incidence.]{.underline}

Day 1: 3/60= 0.05 cases per fish-day

Day 2: 1/57= 0.02 cases per fish-day

Day 3: 3/53= 0.06 cases per fish-day

Day 4: 4/46= 0.09 cases per fish-day

Day 5: 9/35= 0.26 cases per fish-day

\
[b) What is the prevalence of PSD on day 3 and day 5?]{.underline}

(Prevalence= #infected/#population)

Day 1: 3/60= 0.05

Day 2: 4/60=0.07

Day 3: 7/60= 0.12

Day 4: 11/60=.18

Day 5: 20/60= 0.33

\
[c) On which day is the prevalence same as the incidence (except the units)?]{.underline}

Day 1.
