---
title: "JM_DiseaseEcology_Midterm"
format: html
editor: visual
---

## **Disease Ecology FOWS 7200**

Exam 1; October 4, 2024

**1. True or False. If false, explain why the statement is incorrect. (10 points)**

**a) Chagas disease is a protozoal disease that is commonly transmitted by the triatomine bug (Kissing bug). It can also be transmitted by consumption of contaminated food or beverages (feces of infected triatomine bugs). Chagas disease is therefore infectious as well as contagious.**

Chagas disease is infectious. However, it is not contagious. Contagious diseases have animal-animal transmission. Therefore, this above statement is FALSE.

**b) The deer mouse (*Peromyscus maniculatus*) infected with Sin Nombre Virus  do not show any clinical signs, but excrete the virus in their urine, feces and saliva. Humans get infected via aerosolized droppings of an infected rodent. Deer mice with Sin Nombre Virus infection can therefore be described as infected, diseased and infectious.**

The deer mouse can be described as infected because they carry the virus. The deer mouse can also be described as infectious because it can transmit the virus to others. However, it is not considered diseased because it is not showing clinical signs. Therefore, the statement above is FALSE.

**c) Compared to macroparasites, microparasites have a shorter generation time and do not reproduce within the host.**

FALSE. Micro-parasites have short generation times but they have high rates of reproduction within the host. Macro-parasites have low or no direct reproduction within the host.

**d) Epizootic Hemorrhagic disease always causes severe outbreaks in white-trailed deer populations across the US, resulting in high mortalities.**

FALSE. Epizootic Hemorrhagic Disease (EHD) doesn't always result in high mortalities. In the coastal plains of the southeast, there is low mortality with clinical forms of the disease being hoof and rumen lesions.

**e) Using disease models, we can make accurate predictions of how a disease will spread in a real-world host population**.

FALSE. Models are unable to predict with certainty. Models rely on data that can be inaccurate which can lead to uncertainty. Disease modeling is used to given managers a better understanding of how the disease system works. It helps prioritize research and data collection methods as well as serving as a means of assessing and quantifying threats posed by wildlife disease systems.

------------------------------------------------------------------------

**2**. Match the following: (**10 points**)

a\. Elk infected with meningeal worm - **2** 1.Blackhead disease

b\. Effective contact rate - **4** 2. Dead end host

c\. Disease caused by a virus - **3** 3. COVID-19

d\. Disease caused by protozoa - **1** 4. β

e\. Disease caused by a fungus - **6** 5. Rabbit Hemorrhagic disease

6. Aspergillosis

7 .λ (Force of infection)

------------------------------------------------------------------------

**3. What are some of the main challenges in managing wildlife diseases? Explain using relevant examples.(10 points)**

Wildlife disease management is an issue with many layers of complexity. One layer of complexity is the monitoring and surveillance of the disease. Detecting diseases in a population can be difficult to assess due to the remoteness of populations and the elusiveness of the individuals. These issues can be costly and require resources that may not be available to manage the disease effectively. There can be gaps in the knowledge and a lack of data that can also decrease the effective decision making efforts of managers. The ecological cascades that often ripple from wildlife diseases can also be hard to predict and therefore hard to manage for. Lastly, public opinion and public misconceptions can prevent effective policy from becoming a reality.

 

------------------------------------------------------------------------

**4. Refer to the life cycle of *Dicrocoelium dendriticum* fluke of ruminants to answer the following questions:(6 points)**

**a) Name two intermediate hosts in the life cycle of *Dicrocoelium dendriticum*.**

ANSWER: The slug and the ant are the two intermediate host in the life cycle of Dicrocoelium dendriticum.

**b) Name the dead-end host for *Dicrocoelium dendriticum*.**

ANSWER: The cow or the human is the dead end host. The cow and human can harbor the pathogen but do not contribute to the transmission to a new host.

**c) After the infected ant is ingested by a grazing ruminant, the metacercariae excyst in the small intestine and migrate to bile ducts and gall bladder, where they mature into adult flukes and reproduce. The adult flukes start releasing eggs in about 2 months. This interval, from exposure to the metacercariae to eggs being detected in the feces of the host, is known as:**

ANSWER: The pre-patent period. This describes the period between infection with a parasite and the demonstration of the parasite in the body especially as determined by the recovery of an infective form (oocyst or eggs) from the blood or feces.

------------------------------------------------------------------------

**5**. **Compare and contrast the two measures of frequency of disease: Prevalence and incidence. (5 points)**

Prevalence is the number of affected as a proportion of the total population. Prevalence is a snapshot of how many animals have the disease at a point in time.

Incidence is the number of new cases of disease occurring during a fixed period of time divided by the number of animals at risk of developing the disease during that time. Incidence deals only with new cases of disease. It is a measure of risk.

------------------------------------------------------------------------

**6. Calculate the average recovery rate (γ) for the following diseases:**

**a) Measles, average infectious period 8 days. (3 points)**

1/8= 0.125/day

**b) Rotavirus, infectious period 1-3 weeks, average of 2 weeks. (3 points)**

1/14=0.071/day

**The R~0~ for measles is estimated at 15 and 17 for rotavirus. Calculate β for both diseases.(3 points)**

Measles: 15 x 0.125 = 1.875

Rotavirus: 17 x 0.071= 1.207

**Calculate R~eff~ for a measles outbreak in a population with 80% measles vaccination coverage. (3 points)**

**R~0\ =~** 15

Vaccination coverage: 80% or .80

**R~eff~** = 15 x (1 - 0.80) = 3

------------------------------------------------------------------------

**7. *Toxoplasma gondii* is an emerging protozoan parasite of marine mammals. Exposure to this pathogen has been documented in pinniped (seals and sea lions) populations world over. Lindsay et al. did a serosurvey of Australian sea lions (*Neophoca cinerea*) using archived sera samples collected between 2017-18 from Seal Bay, Olive Island and Dangerous Reef.**

**A total of 184 pups were sampled from these three sites. Site wise distribution of pups sampled is given here:**

**Sera samples from all the pups were seronegative for *T. gondii* antibodies when tested using a commercially available modified agglutination test (MAT).**

**a) Based on these findings, how confident are you that none of the pups at these sites are exposed to *T. gondii*? (3 points)**

Even though all sera samples were seronegative, I do not believe that it is a guarantee that there has been 0 exposure among the population. I am not confident that none of the pups at these sites were exposed to T. gondii because the sample size for each site is considerably low. I chose to seek the appropriate sample size using a 95% confidence interval for each given populations. The sample sizes for each site were low.

**b)How many more samples are necessary from the Olive Island population to be 99% confident that not a single pup has been exposed to *T. gondii*?(4 points)**

Olive Island sample size: 65

Olive Island population: 101

To be 99% confident at a 1% prevalence, it is necessary to have a sample size of 100.

**c) Estimate the upper bound of prevalence for exposure to *T. gondii* for each of these populations. Also, provide the confidence level for these prevalence values. (6 points)**

Formula: Upper bound prevalence = (X+z^2^/2)/(n+ z\^2/2)

[Seal Bay:]{.underline}

Population: 232

Sample size: 98

Positive cases: 0

99% confidence level (Z score = 2.576)

(3.317888)/(98+6.635776)=(3.317888)/(104.635776)=0.0317 or 3.17%

Seal bay upper bound prevalence = 3.17% (99% confidence)

[Olive Island:]{.underline}

Population: 101

Sample size: 65

Positive cases: 0

(3.31788)/(98+6.635776)=(3.317888)/(71.635776)=0.0463 or 4.63%

Olive island upper bound prevalence = 4.63% (99% confidence)

[Dangerous Reef:]{.underline}

Population: 338

Sample size: 21

Positive cases: 0

(3.31788)/(21+6.635776)=(3.31788)/(27.635776)= 0.120 or 12%

Dangerous reef upper bound prevalence = 12% (99% confidence)

------------------------------------------------------------------------

**8. Mitch manages a high-fenced deer facility in Texas. In 2015, an outbreak of deer fibroma started in this captive deer facility. The following data was recorded by Mitch:**

**Note that there is no disease-related mortality. All deer without visible fibroma are considered susceptible to the disease.**

| Year | Incidence (cases per deer-year) | Prevalence             |
|------|---------------------------------|------------------------|
| 2015 | 3/225=0.013 or 1.33%            | 3/255=0.013 or 1.33%   |
| 2016 | 7/350=0.02 or 2.00%             | 9/350=0.0257 or 2.57%  |
| 2017 | 8/283=0.028 or 2.83%            | 13/283=0.0459 or 4.59% |
| 2018 | 6/170=0.035 or 3.53%            | 12/170=0.070 or 7.06%  |
| 2019 | 1/245=0.004 or 0.41%            | 5/245=0.020 or 2.04%   |
| 2020 | 0/220 = 0.00%                   | 6/220=0.027 or 2.73%   |
| 2021 | 1/255 = 0.0039 or 0.39%         | 6/255=0.023=2.35%      |

**a) Which year has the highest incidence of deer fibroma? Make sure you write appropriate unit for the incidence value. (6 points)**

The highest incidence for deer fibroma is in 2018. The incidence was 0.035 cases per deer-year

**b) When is the prevalence lowest? Write the unit for prevalence if applicable. (6 points)**

The prevalence was lowest in 2015. The prevalence in 2015 was 0.013 or 1.33%

------------------------------------------------------------------------

**9**. **What are the basic assumptions of compartmental models? Provide a few examples of different types of compartmental models. (10 points)**

Basic assumptions of compartmental models are as follows:

1\) A closed host population

2\) Mixing in population that is homogenenous

3\) Infected host is instantly infectious

4\) Recovered individuals have life-long immunity

5\) Well defined compartments

There are different types of compartmental models such as:

1\) SIR models: This model captures the transition from Susceptible-Infected-Recovered.

2\) SEIR models: This model captures the transition from Susceptible-Exposed-Infected-Recovered. These models are useful when modeling a disease that has an incubation period.

3\) SIRV models: This model captures the transition from Susceptible-Infected-Recovered-Vaccinated. This model is similar to the SIR model, but it considers vaccination as a vital role in the disease dynamic.

------------------------------------------------------------------------

**10**. **Domestic chickens may carry *Histomonas meleagridis* but may not demonstrate any clinical signs. Such hosts are: (2 points)**

**1) diseased**

**2) infected but not diseased**

**3) carriers**

**4) neither infected nor diseases**

**Choose [all]{.underline} the correct answers.**

Domestic chickens that may carry Histomonas meleagridis are infected but not diseased. They are also carriers. The chickens are not displaying clinical signs therefore, they are not diseased.

------------------------------------------------------------------------

**11**. **Define R~0~. Estimate R~0~ for the two scenarios in the table below. A red circle represents an infectious case, and blue circles are susceptibles; an arrow indicates transmission. Explain your findings in the context of real-world utility of R~0~. (10 points)**

R~0~ : The average number of new infections caused by a single infected individual in a fully susceptible population. R~0~ is a metric of potential transmissibility of infectious agents.

If R~0~ is greater than 1, the infection has the potential to spread. If R~0~ is less than 1, the infection will likely fade out.

[Scenario 1:]{.underline}

5 Infectious cases

10 susceptibles

10/5 = 2

[Scenario 2:]{.underline}

5 Infectious cases

10 susceptibles

10/5 = 2

Therefore, the R~0~ = 2 in both scenarios. Each individual is going to infect an average of 2 individuals in the population. The infection has the potential to spread. However, R~0~ can be lowered below 1 by public health measures such as vaccines.

------------------------------------------------------------------------

**Bonus question:**

**12. The Dutch harbor seal population is estimated to be around 5400 with \~50% adults. Seals are susceptible to phocine distemper virus (PDV), but an estimated 40% of the adults in this population are immune to PDV by virtue of prior natural infection.**

**How many seals in this population should be vaccinated in order to achieve herd immunity sufficient to prevent an outbreak of PDV in this population if the R0 is estimated to be \~3?**

**Assume that all the adult seals that have survived prior PDV infection are tagged, and hence identifiable.**

Herd Immunity Threshold= 1-1/R~0~

1-1/3= 1- 0.333= 0.667 = 67% of population needs to be immune to achieve herd immunity.

0.667 x 5400 seals = \~3,600 seals need to be immune to achieve herd immunity.

40% of adult seals (2,700 adults) are already immune = .40 x 2700= 1080

3,600 - 1,080 = 2,520 seals must be vaccinated in order to achieve herd immunity.
